name: Deploy to EC2

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.232.41.47 << 'EOF'
            cd /home/ubuntu
            if [ ! -d "backend-rest-api-ec2-git-runner" ]; then
              git clone https://github.com/Faaiz-uddin/backend-rest-api-ec2-git-runner.git
            fi
            cd backend-rest-api-ec2-git-runner
            git pull origin master
            npm install
            pm2 restart backend || pm2 start server.js --name backend
          EOF